import 'package:moyen_express/resources/exports/index.dart';
import 'package:moyen_express/view_model/controllers/inquiry_detail/inquiry_detail_controller.dart';

class InquiryDetail extends GetView<InquiryDetailController> {
  const InquiryDetail({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(title: Strings.INQUIRY_DETAIL.tr),
      body: Padding(
          padding: const EdgeInsets.only(left: 10.0, right: 10.0),
          child: controller.isReplied == 0
              ? Column(
                  children: [
                    Expanded(
                      child: SingleChildScrollView(
                        child: Column(
                          children: [
                            const SpaceH8(),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.productName,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.PRODUCT_NAME.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.quantity,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.QUANTITY.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.deliveryAddress,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.DELIVERY_ADDRESS.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 2,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.myNote,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.MY_NOTE.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            const SpaceH4(),
                          ],
                        ),
                      ),
                    ),
                    CustomButton.solid(
                      showIconOnRight: true,
                      text: Strings.ACCEPT_PAY.tr,
                      backgroundColor: AppColors.primaryColor,
                      textColor: AppColors.white,
                      radius: 5.0,
                      // onTapAsync: () async =>
                    ),
                    const SpaceH10(),
                  ],
                )
              : Column(
                  children: [
                    Expanded(
                      child: SingleChildScrollView(
                        child: Column(
                          children: [
                            const SpaceH8(),

                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.productName1,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.PRODUCT_NAME.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.quantity1,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.QUANTITY.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.perUnitPrice,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.PER_UNIT_PRICE.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.totalPrice,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.TOTAL_PRICE.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.deliveryCharges,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.DELIVERY_CHARGES.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 2,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.estDeliveryDays,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.EXPECTED_DELIVERY_DAYS.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.deliveryAddress1,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.DELIVERY_ADDRESS.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.myNote1,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.MY_NOTE.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            CustomTextFormField(
                              readOnly: true,
                              controller: controller.sellerNote,
                              isRequired: true,
                              height: Sizes.HEIGHT_16,
                              labelText: Strings.SELLER_NOTE.tr,
                              labelColor: AppColors.black,
                              textColor: AppColors.black,
                              cursorColor: AppColors.black,
                              maxLines: 1,
                              borderRadius: 7.0,
                              errorColor: AppColors.error,
                              enableBorderColor: AppColors.black,
                              focusBorderColor: AppColors.primaryColor,
                              textInputAction: TextInputAction.next,
                            ),
                            const SpaceH4(),
                          ],
                        ),
                      ),
                    ),
                    CustomButton.solid(
                      //  margin: const EdgeInsets.all(5.0),
                      showIconOnRight: true,
                      text: Strings.ACCEPT_PAY.tr,
                      backgroundColor: AppColors.primaryColor,
                      textColor: AppColors.white,
                      radius: 5.0,
                      // onTapAsync: () async =>
                    ),
                    const SpaceH10(),
                  ],
                )),
    );
  }
}
