name: moyen_express
description: "A new Flutter project."

publish_to: "none"

version: 2.6.6+31

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get: ^4.6.6
  http: ^0.13.3 
  logger: ^2.0.2+1
  responsive_framework: ^0.2.0
  infinite_scroll_pagination: ^4.0.0
  app_settings: ^5.1.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.8
  get_storage: ^2.1.1
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  share_plus: ^7.2.1
  flutter_html: ^3.0.0-beta.2
  flutter_native_splash: ^2.3.8
  encrypt: ^5.0.3
  lottie: ^2.7.0
  flutter_cache_manager: ^3.3.1
  flutter_form_builder: ^9.1.1
  enefty_icons: ^1.0.7
  form_field_validator: ^1.1.0
  carousel_slider: ^5.0.0
  flutter_config: ^2.0.2
  flutter_spinkit: ^5.2.0
  firebase_core: ^2.24.2
  smooth_page_indicator: ^1.1.0
  slide_countdown: ^1.5.0
  dropdown_search: ^5.0.6
  pinput: ^3.0.1
  panara_dialogs: ^0.1.4
  country_state_city_pro: ^0.0.6
  country_code_picker: ^3.0.0
  file_picker: ^6.1.1
  marquee: ^2.2.3
  flutter_bounce: ^1.1.0
  flutter_polygon: ^0.3.0+2
  flutter_stripe: ^10.1.1
  like_button: ^2.0.5
  shared_preferences: ^2.2.3
  flutter_file_downloader: ^1.2.1
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.3
  flutter_paypal: ^0.2.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.1+2
  googleapis_auth: ^1.4.1
  flutter_paypal_payment: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app_icons/app_launcher.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icons/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/lottie/
    - assets/gif/
    - assets/on_boarding/
    - assets/login/
    - assets/home/
    - assets/images/
    - assets/dashboard/
    - assets/auction/
    - assets/technician/
    - assets/my_orders/
    - assets/contact/
    - assets/about/
    - assets/store/
    - assets/get_quote/
    - assets/cscpicker/
    - assets/parcel_detail/
    - assets/coming_soon/
    - assets/payments/
    - assets/search/
   

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic

flutter_native_splash:
  image: assets/app_icons/app_launcher.png
  color: "#FFFFFF"
  color_dark: "#FFFFFF"

  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/app_icons/app_launcher.png

  ios: true
