// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCupB9zGZrenhAbmctpDDc5vmL06TvgWJA',
    appId: '1:915649795976:web:643995aa6ababe5dd88c3d',
    messagingSenderId: '915649795976',
    projectId: 'moyenxpresscustomer',
    authDomain: 'moyenxpresscustomer.firebaseapp.com',
    storageBucket: 'moyenxpresscustomer.appspot.com',
    measurementId: 'G-GP0D7MRFQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzhkh8o0JkSWzS56jqCa1eja-9x1VELnI',
    appId: '1:915649795976:android:53a46f6747147482d88c3d',
    messagingSenderId: '915649795976',
    projectId: 'moyenxpresscustomer',
    storageBucket: 'moyenxpresscustomer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbI-s9DuxPItZGVnwY0tum-Qh2wluB2f4',
    appId: '1:915649795976:ios:99e26bb076c99a0ed88c3d',
    messagingSenderId: '915649795976',
    projectId: 'moyenxpresscustomer',
    storageBucket: 'moyenxpresscustomer.appspot.com',
    iosBundleId: 'com.example.moyenExpress',
  );
}
